site_name: Science & Disinformation Briefs

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: orange
  font:
    text: Merriweather
    code: Roboto Mono
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy

extra_css:
  - css/substack.css

nav:
  - Home: index.md

  - Articles:
      - AI and Disinformation: article1.md
      - Political Disinformation: article2.md
      - Health Misinformation: article3.md
      - Counter-Disinformation: article4.md

  - About:
      - Methodology: methodology.md
